# Basic options
title: Matt's Blog
author: Matthew McCormick
email: cryptomasterleviathan@gmail.com
description: My thoughts and notes on technology
twitter_username: CryptomasterLev
github_username: CryptomasterLeviathan

paginate: 5
permalink: /:year/:month/:day/:title.html

# Build settings
theme: minima
